### ISSUE TITLE
完成 a022: 迴文

### ISSUE THREAD

**Issue by b00902130** [CHometeach/ZeroJudge#21]

**Comment by HuangJi** [comment]
內容 ：

迴文的定義為正向，反向讀到的字串均相同

如：abba , abcba ... 等就是迴文

 請判斷一個字串是否是一個迴文？

輸入說明 ： 
一個字串(長度 < 1000)

輸出說明 ： 
yes or no

範例輸入 ：  help
abba
abcd
範例輸出:
yes
no
提示 ： 
標籤:
字串 迴文
出處: 
(管理：jiangsir)
